### ISSUE TITLE
Unable to use `.json` on pydantic Model containing ormar Model with ForeignKey

### ISSUE THREAD

**Issue by Shmookoff** [collerek/ormar#746] opened 2022-07-17 04:51 UTC
**Describe the bug**
Using `.json()` on a pydantic `Model` that has ormar `Model` with a `ForeignKey` in its fields results in
`AttributeError: 'Model' object has no attribute '_orm'`.

**To Reproduce**
```py
import asyncio

import databases
import ormar
import pydantic
import sqlalchemy

DATABASE_URL = "sqlite:///db.sqlite"

database = databases.Database(DATABASE_URL)
metadata = sqlalchemy.MetaData()


class OrmarModelA(ormar.Model):
    class Meta:
        database = database
        metadata = metadata

    id: int = ormar.Integer(primary_key=True)


class OrmarModelB(ormar.Model):
    class Meta:
        database = database
        metadata = metadata

    id: int = ormar.Integer(primary_key=True)
    a: OrmarModelA = ormar.ForeignKey(OrmarModelA)


engine = sqlalchemy.create_engine(DATABASE_URL)
metadata.drop_all(engine)
metadata.create_all(engine)


class PydanticModel(pydantic.BaseModel):
    ormar_b: OrmarModelB


async def main():
    await database.connect()

    ormar_a = await OrmarModelA.objects.create()
    ormar_b = await OrmarModelB.objects.create(a=ormar_a)

    pydantic_object = PydanticModel(ormar_b=ormar_b)
    json = pydantic_object.json()
    print(json)

    await database.disconnect()


asyncio.run(main())

```

**Traceback**
```py
Traceback (most recent call last):
  File "/home/shmoo/projects/kormipravilno/telegram-bot/main.py", line 55, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/shmoo/projects/kormipravilno/telegram-bot/main.py", line 49, in main
    json = pydantic_object.json()
  File "pydantic/main.py", line 487, in pydantic.main.BaseModel.json
  File "pydantic/main.py", line 843, in _iter
  File "pydantic/main.py", line 718, in pydantic.main.BaseModel._get_value
  File "/home/shmoo/.cache/pypoetry/virtualenvs/telegram-bot-nW6pW6aK-py3.10/lib/python3.10/site-packages/ormar/models/newbasemodel.py", line 767, in dict
    dict_instance = self._extract_nested_models(
  File "/home/shmoo/.cache/pypoetry/virtualenvs/telegram-bot-nW6pW6aK-py3.10/lib/python3.10/site-packages/ormar/models/newbasemodel.py", line 659, in _extract_nested_models
    nested_model = getattr(self, field)
  File "/home/shmoo/.cache/pypoetry/virtualenvs/telegram-bot-nW6pW6aK-py3.10/lib/python3.10/site-packages/ormar/models/newbasemodel.py", line 193, in __getattr__
    return super().__getattribute__(item)
  File "/home/shmoo/.cache/pypoetry/virtualenvs/telegram-bot-nW6pW6aK-py3.10/lib/python3.10/site-packages/ormar/models/descriptors/descriptors.py", line 105, in __get__
    if self.name in instance._orm:
  File "/home/shmoo/.cache/pypoetry/virtualenvs/telegram-bot-nW6pW6aK-py3.10/lib/python3.10/site-packages/ormar/models/newbasemodel.py", line 193, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'OrmarModelB' object has no attribute '_orm'
```

**Expected behavior**
Using `.json()` on a pydantic `Model` that has ormar `Model` with a `ForeignKey` in its fields should result in a JSON representation of said pydantic `Model`.

**Versions (please complete the following information):**
 - Database backend used **sqlite**
 - Python version **3.10.2**
 - `ormar` version **0.11.2**
 - `pydantic` version **1.9.1**

**Additional context**
Using `.json` on a pydantic Model that has ormar `Model` with **no** `ForeignKey` **doesn't** result in an exception.
As of creating the issue, I haven't thought through the pipeline of `.json`. The issue really is about `.dict`, that doesn't really matter though.

**Comment by collerek** [comment] 2022-07-19 15:11
Duplicate of https://github.com/collerek/ormar/issues/340
As of now, you cannot nest ormar models in pydantic models.

**Closed by collerek** 2022-07-19 15:11 UTC
Labels: bug
