### ISSUE TITLE
Impossible to remove ForeignKey relation

### ISSUE THREAD

**Issue by onerandomusername** [collerek/ormar#720] opened 2022-06-28 12:13 UTC
**Describe the bug**
ForeignKey relations are impossible to remove. No matter what I try, I cannot remove a ForeignKey from an instance.

**To Reproduce**

```py
import asyncio
import datetime
from typing import TYPE_CHECKING, List, Optional

import databases
import ormar
import sqlalchemy


DB_URL = databases.DatabaseURL("sqlite:///bug.sql")


database = databases.Database(DB_URL)
metadata = sqlalchemy.MetaData()


class BaseMeta(ormar.ModelMeta):
    metadata = metadata
    database = database


class Rollout(ormar.Model):
    """Represents a feature rollout."""

    class Meta(BaseMeta):
        tablename: str = "rollouts"

    id: int = ormar.Integer(autoincrement=True, primary_key=True)  # type: ignore
    name: str = ormar.String(max_length=100, unique=True)  # type: ignore
    active: bool = ormar.Boolean(default=False, nullable=False)


class Feature(ormar.Model):
    """Represents a bot feature."""

    class Meta(BaseMeta):
        tablename: str = "features"

    name: str = ormar.String(primary_key=True, max_length=50)  # type: ignore
    rollout: Optional[Rollout] = ormar.ForeignKey(Rollout, nullable=True)  # type: ignore


engine = sqlalchemy.create_engine(str(DB_URL))
metadata.drop_all(engine)
metadata.create_all(engine)


async def main():

    # set up with some prelimary data
    feature = await Feature.objects.create(name="QUICKLINKING")
    rollout = await Rollout.objects.create(name="public_fast_links")

    print(f"{feature.rollout = }")
    print(f"{rollout = }")

    # now link the rollout to the feature
    feature.rollout = rollout
    await feature.update()
    print("linked the feature to the rollout")

    print(f"{feature.rollout = }")

    # now try to unlink the rollout
    
    await feature.update(rollout=None)
    print("attempted to remove the rollout reference")
    print(f"{feature.rollout = }")
  
    # we can also use feature.rollout = None with absolutely no change
    feature.rollout = None
    print(f"{feature.rollout = }")

if __name__ == "__main__":
    asyncio.run(main())
```

**Expected behavior**
The ForeignKey should be removed so i don't continue to have it!

**Screenshots**
![image](https://user-images.githubusercontent.com/71233171/176175383-bb6328c1-f817-46d4-8669-a6df22b02f7f.png)

**Versions (please complete the following information):**
 - Database backend used: postgres and sqlite
 - Python version -- 3.9
 - `ormar` version -- 0.11.2
 - `pydantic` version -- 1.9.1
 - if applicable `fastapi` version

**Additional context**

**Comment by collerek** [comment] 2022-06-29 12:55
Duplicate of #301. You need to explicitly call remove.

**Closed by collerek** 2022-06-29 12:55 UTC
Labels: bug
