### ISSUE TITLE
json field set null

### ISSUE THREAD

**Issue by ponytailer** [collerek/ormar#549] opened 2022-01-27 03:32 UTC
```

class ItemConfig(ormar.Model):

    pairs = ormar.Json()

it = await ItemConfig(pairs=None).save()

```

In database(pg):

the `pairs` was updated to 
![image](https://user-images.githubusercontent.com/6038418/151287108-0c9bd7aa-6db0-4a8f-a67f-cdcef7b8eec5.png)

not the 
![image](https://user-images.githubusercontent.com/6038418/151287153-e19e8d78-7eff-4c66-bc17-4e43f5a5a2de.png)

so,

when execute the sql:  `select * from item_config where pairs is null`, no result. why?

**Comment by collerek** [comment] 2022-01-27 08:00
Duplicate of #529 - it's a bug

**Closed by collerek** 2022-01-27 08:00 UTC
Labels: bug
